In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.datasets import load_digits

In [97]:
data = load_digits()

In [98]:
X = pd.DataFrame(data.data)

In [99]:
y = pd.DataFrame(data.target)

In [100]:
from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(X)


In [242]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 55)
x_std = pca.fit_transform(x)

In [243]:
df = pd.DataFrame(data = x_std)
df.head()

0         1         2         3         4         5         6   \
0  1.914214 -0.954502 -3.946035  2.028723 -0.267173  0.530327 -1.415321   
1  0.588980  0.924636  3.924755 -1.779850 -0.993430 -0.675652  1.878565   
2  1.302039 -0.317189  3.023333 -2.043376 -2.081155  0.935121 -1.296200   
3 -3.020770 -0.868772 -0.801744 -2.187039 -0.556813  0.727124  0.959766   
4  4.528949 -1.093480  0.973121 -1.419510 -1.715106  1.431592  1.073649   

         7         8         9     ...           45        46        47  \
0  1.496062  0.124914 -0.822246    ...    -0.147594  0.100290  0.420029   
1  0.556336  1.079877  0.087451    ...     0.022378 -0.532894 -0.138601   
2  1.156160  0.785606 -1.099206    ...    -0.646057 -0.568704  0.344729   
3 -1.382638  0.259075  0.744555    ...     0.430608 -0.184575  0.019432   
4 -0.968240 -1.660216  1.174593    ...     0.831098  0.853649 -0.345438   

         48        49        50        51        52        53        54  
0 -0.179378  0.154212  0.470459  0.128759 -0.108361  0.017914  0.217284  
1 -0.112084  0.764731  0.058997 -0.062811 -0.048471  0.395305  0.005322  
2  0.180769  0.495403 -0.379882 -0.006784 -0.081455  0.310967  0.178624  
3 -0.160415  0.144037  0.339174  0.347814  0.128994  0.759133 -0.115443  
4  0.169067  0.279853  0.227091  0.396234  0.172144 -0.281930 -0.335099  

[5 rows x 55 columns]

In [244]:
from sklearn.model_selection import train_test_split
trainX, testX, trainy, testy = train_test_split( x_std,y, test_size=0.20,random_state=7)

In [245]:
from sklearn.linear_model import LogisticRegression

In [246]:
LR = LogisticRegression()

In [247]:
LR.fit(trainX,trainy)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [248]:
pred = LR.predict(testX)

In [249]:
from sklearn import metrics


In [250]:
lr = LogisticRegression()

In [251]:
metrics.accuracy_score(pred,testy)

0.94722222222222219

In [180]:
print(metrics.confusion_matrix(pred,testy))

[[43  0  0  0  0  0  0  0  0  0]
 [ 0 38  0  1  0  0  0  0  3  1]
 [ 0  1 39  0  0  0  0  0  1  0]
 [ 0  0  0 32  0  0  0  0  3  0]
 [ 0  0  0  0 36  0  0  0  0  0]
 [ 0  0  0  0  0 27  0  0  1  2]
 [ 0  0  0  0  0  0 27  0  0  0]
 [ 0  0  1  0  0  0  0 33  2  0]
 [ 0  1  0  1  0  0  1  0 33  0]
 [ 0  2  0  0  1  1  0  0  0 29]]


In [181]:
print(metrics.classification_report(pred,testy))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        43
          1       0.90      0.88      0.89        43
          2       0.97      0.95      0.96        41
          3       0.94      0.91      0.93        35
          4       0.97      1.00      0.99        36
          5       0.96      0.90      0.93        30
          6       0.96      1.00      0.98        27
          7       1.00      0.92      0.96        36
          8       0.77      0.92      0.84        36
          9       0.91      0.88      0.89        33

avg / total       0.94      0.94      0.94       360



0.99332220367278801