In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.datasets import load_digits

In [3]:
digit = load_digits()
X = pd.DataFrame(digit.data)
y = pd.DataFrame(digit.target)
y = y.values.reshape(1797)
y.shape

(1797,)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30, random_state = 0)
y_train.shape

(1257,)

In [7]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()
reg.fit(X_train,y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [8]:
pred = reg.predict(X_test)
#result = pd.DataFrame({"Predicted":pred,"Actual":y_test})


In [9]:
from sklearn import model_selection


kfold = model_selection.KFold(n_splits = 10, random_state =7)

Classification accuracy

In [11]:
results = model_selection.cross_val_score(reg,X,y,cv = kfold,scoring='accuracy')
results


array([ 0.90555556,  0.95      ,  0.89444444,  0.91666667,  0.94444444,
        0.97222222,  0.97777778,  0.95530726,  0.8603352 ,  0.93854749])

In [12]:
results.sum()/10


0.93153010552451898

Logrithmic loss

In [13]:
results = model_selection.cross_val_score(reg,X,y,cv = kfold,scoring='neg_log_loss')
results

array([-0.45798961, -0.14435058, -0.61749705, -0.27323142, -0.27594697,
       -0.12815811, -0.11024468, -0.1233365 , -0.62592303, -0.68553964])

In [14]:
results.sum()/10

-0.34422175750181627

Confusion metric

In [15]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,pred))

[[45  0  0  0  0  0  0  0  0  0]
 [ 0 47  0  0  0  0  2  0  3  0]
 [ 0  0 51  2  0  0  0  0  0  0]
 [ 0  0  1 52  0  0  0  0  0  1]
 [ 0  0  0  0 48  0  0  0  0  0]
 [ 0  1  0  0  0 55  1  0  0  0]
 [ 0  1  0  0  0  0 59  0  0  0]
 [ 0  1  0  1  1  0  0 50  0  0]
 [ 0  3  1  0  0  0  0  0 55  2]
 [ 0  0  0  1  0  1  0  0  2 53]]


In [16]:
from sklearn.metrics import classification_report
report = classification_report(y_test,pred)
print(report)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        45
          1       0.89      0.90      0.90        52
          2       0.96      0.96      0.96        53
          3       0.93      0.96      0.95        54
          4       0.98      1.00      0.99        48
          5       0.98      0.96      0.97        57
          6       0.95      0.98      0.97        60
          7       1.00      0.94      0.97        53
          8       0.92      0.90      0.91        61
          9       0.95      0.93      0.94        57

avg / total       0.95      0.95      0.95       540



Mean absolute, mean square error

In [17]:
from sklearn import metrics
from math import sqrt

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

y_pred = regressor.predict(X_test)

mse = metrics.mean_squared_error(y_test,y_pred)
rms = sqrt(metrics.mean_squared_error(y_test,y_pred))
mae = metrics.mean_absolute_error(y_test,y_pred)
print("Mean squared error %f Root mean square error %f mean absolute error %f" %(mse,rms,mae))

Mean squared error 3.452475 Root mean square error 1.858084 mean absolute error 1.457900


R2 metric

In [18]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits = 10, random_state =7)
results = model_selection.cross_val_score(regressor,X,y,cv = kfold,scoring='r2')# for regression r2 is coeffecient of determination it determines how good is model fit 
results

array([ 0.40105499,  0.63102463,  0.57072313,  0.59629035,  0.54519634,
        0.67174215,  0.61763556,  0.47611004,  0.4236549 ,  0.41044286])