In [1]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.svm import SVC
from sklearn import datasets

In [2]:
digits = datasets.load_digits()

In [3]:
X = digits.data

In [4]:
y = digits.target

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.30, random_state = 7)

RBF model

In [26]:
model = SVC(C=2)

In [27]:
model.fit(X_train,y_train)

SVC(C=2, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
pred=model.predict(X_test)

In [29]:
metrics.accuracy_score(y_test,pred)

0.45000000000000001

In [211]:
model.score(X_test,y_test)

0.45000000000000001

In [214]:
from sklearn import model_selection

kfold = model_selection.KFold(n_splits = 10, random_state = 7)

results = model_selection.cross_val_score(model,X,y,cv= kfold,scoring = "accuracy")
results.sum()/10

0.49865611421477352

In [218]:
from sklearn.metrics import classification_report
report = classification_report(y_test,pred)
print(report)

             precision    recall  f1-score   support

          0       1.00      0.48      0.64        61
          1       1.00      0.35      0.51        55
          2       1.00      0.34      0.51        53
          3       1.00      0.69      0.82        52
          4       1.00      0.33      0.49        58
          5       0.14      1.00      0.24        48
          6       1.00      0.67      0.80        48
          7       1.00      0.45      0.62        49
          8       1.00      0.03      0.06        62
          9       1.00      0.33      0.50        54

avg / total       0.92      0.45      0.51       540



In [224]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,pred))

[[29  0  0  0  0 32  0  0  0  0]
 [ 0 19  0  0  0 36  0  0  0  0]
 [ 0  0 18  0  0 35  0  0  0  0]
 [ 0  0  0 36  0 16  0  0  0  0]
 [ 0  0  0  0 19 39  0  0  0  0]
 [ 0  0  0  0  0 48  0  0  0  0]
 [ 0  0  0  0  0 16 32  0  0  0]
 [ 0  0  0  0  0 27  0 22  0  0]
 [ 0  0  0  0  0 60  0  0  2  0]
 [ 0  0  0  0  0 36  0  0  0 18]]


linear model

In [62]:
model1 = SVC(kernel='linear')

In [63]:
model1.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [64]:
pred1=model1.predict(X_test)

In [65]:
metrics.accuracy_score(y_test,pred1)

0.95925925925925926

In [210]:
model1.score(X_test,y_test)

0.95925925925925926

In [215]:
from sklearn import model_selection

kfold = model_selection.KFold(n_splits = 10, random_state = 7)

results = model_selection.cross_val_score(model1,X,y,cv= kfold,scoring = "accuracy")
results.sum()/10

0.96382681564245798

In [219]:
from sklearn.metrics import classification_report
report = classification_report(y_test,pred1)
print(report)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        61
          1       0.94      0.93      0.94        55
          2       0.98      1.00      0.99        53
          3       0.96      0.96      0.96        52
          4       0.98      0.98      0.98        58
          5       0.89      1.00      0.94        48
          6       1.00      1.00      1.00        48
          7       0.96      0.96      0.96        49
          8       0.90      0.87      0.89        62
          9       0.98      0.91      0.94        54

avg / total       0.96      0.96      0.96       540



sigmoid function

In [153]:
model2 = SVC(C=13,gamma=0.0001,kernel='sigmoid')

In [154]:
model2.fit(X_train,y_train)

SVC(C=13, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [155]:
pred2 = model2.predict(X_test)

In [156]:
metrics.accuracy_score(y_test,pred2)

0.97777777777777775

In [212]:
model2.score(X_test,y_test)

0.97777777777777775

In [216]:
from sklearn import model_selection

kfold = model_selection.KFold(n_splits = 10, random_state = 7)

results = model_selection.cross_val_score(model,X,y,cv= kfold,scoring = "accuracy")
results.sum()/10

0.49865611421477352

In [220]:
from sklearn.metrics import classification_report
report = classification_report(y_test,pred2)
print(report)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        61
          1       0.93      0.98      0.96        55
          2       1.00      1.00      1.00        53
          3       0.98      1.00      0.99        52
          4       0.98      1.00      0.99        58
          5       0.94      1.00      0.97        48
          6       1.00      0.98      0.99        48
          7       0.98      0.98      0.98        49
          8       0.98      0.89      0.93        62
          9       0.98      0.96      0.97        54

avg / total       0.98      0.98      0.98       540



In [223]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,pred))

[[29  0  0  0  0 32  0  0  0  0]
 [ 0 19  0  0  0 36  0  0  0  0]
 [ 0  0 18  0  0 35  0  0  0  0]
 [ 0  0  0 36  0 16  0  0  0  0]
 [ 0  0  0  0 19 39  0  0  0  0]
 [ 0  0  0  0  0 48  0  0  0  0]
 [ 0  0  0  0  0 16 32  0  0  0]
 [ 0  0  0  0  0 27  0 22  0  0]
 [ 0  0  0  0  0 60  0  0  2  0]
 [ 0  0  0  0  0 36  0  0  0 18]]


polynomial function

In [205]:
model3 = SVC(kernel='poly')

In [206]:
model3.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [207]:
pred3 = model3.predict(X_test)

In [208]:
metrics.accuracy_score(y_test,pred3)

0.98148148148148151

In [213]:
model3.score(X_test,y_test)

0.98148148148148151

In [217]:
from sklearn import model_selection

kfold = model_selection.KFold(n_splits = 10, random_state = 7)

results = model_selection.cross_val_score(model,X,y,cv= kfold,scoring = "accuracy")
results.sum()/10

0.49865611421477352

In [221]:
from sklearn.metrics import classification_report
report = classification_report(y_test,pred3)
print(report)

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        61
          1       0.95      1.00      0.97        55
          2       1.00      1.00      1.00        53
          3       0.98      1.00      0.99        52
          4       0.98      1.00      0.99        58
          5       0.94      1.00      0.97        48
          6       1.00      1.00      1.00        48
          7       0.98      1.00      0.99        49
          8       0.98      0.92      0.95        62
          9       1.00      0.93      0.96        54

avg / total       0.98      0.98      0.98       540



In [222]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,pred3))

[[60  0  0  0  1  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  0 52  0  0  0  0  0  0]
 [ 0  0  0  0 58  0  0  0  0  0]
 [ 0  0  0  0  0 48  0  0  0  0]
 [ 0  0  0  0  0  0 48  0  0  0]
 [ 0  0  0  0  0  0  0 49  0  0]
 [ 0  3  0  0  0  1  0  1 57  0]
 [ 0  0  0  1  0  2  0  0  1 50]]
