In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.datasets import load_iris

In [8]:
data = load_iris()

In [18]:
X=pd.DataFrame(data.data, columns = data.feature_names)

In [24]:
y=pd.DataFrame(data.target)

In [25]:
X.shape,y.shape

((150, 4), (150, 1))

In [26]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [27]:
y.head()

0
0  0
1  0
2  0
3  0
4  0

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20)

gini criterion for decision tree



In [30]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [31]:
y_pred = classifier.predict(X_test)

In [43]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics

In [44]:
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))


[[12  0  0]
 [ 0 10  0]
 [ 0  1  7]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.91      1.00      0.95        10
          2       1.00      0.88      0.93         8

avg / total       0.97      0.97      0.97        30



In [45]:
metrics.accuracy_score(y_pred,y_test)

0.96666666666666667

entropy criterion for decision tree

In [32]:
classifier1 = DecisionTreeClassifier(criterion='entropy')

In [33]:
classifier1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [46]:
pred1 = classifier1.predict(X_test)


In [48]:
print(classification_report(y_pred,y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.91      1.00      0.95        10
          2       1.00      0.88      0.93         8

avg / total       0.97      0.97      0.97        30



In [49]:
print(confusion_matrix(y_pred,y_test))

[[12  0  0]
 [ 0 10  0]
 [ 0  1  7]]


In [50]:
print(metrics.accuracy_score(y_pred,y_test))

0.966666666667


In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
X['species'] = pd.Categorical.from_codes(data.target,data.target_names)

In [54]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [55]:
X['is_train'] = np.random.uniform(0,1,len(X))

In [56]:
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa  0.541765  
1  setosa  0.108110  
2  setosa  0.528632  
3  setosa  0.070007  
4  setosa  0.970915

In [128]:
train, test =X[X['is_train']>0.75], X[X['is_train']<0.75]

In [137]:
features = X.columns[0:4]
features.shape



(4,)

In [138]:
y = pd.factorize(train.species)[0]

gini criterion for random forest

In [139]:
clf = RandomForestClassifier(n_jobs=2,random_state=1)

In [140]:
clf.fit(train[features],y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [146]:
pred2 = data.target_names[clf.predict(test[features])]

In [147]:
print(confusion_matrix(pred2,test['species']))

[[34  0  0]
 [ 0 36  4]
 [ 0  0 36]]


In [148]:
print(metrics.accuracy_score(pred2,test['species']))

0.963636363636


entropy criterion for random forest

In [ ]:
clf2 = RandomForestClassifier(criterion = 'entropy')

In [151]:
clf2.fit(train[features],y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [152]:
pred3 = data.target_names[clf2.predict(test[features])]

In [153]:
print(metrics.accuracy_score(pred3,test['species']))

0.927272727273
